# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: lint
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.21.0
            sudo cp ./bin/golangci-lint $GOPATH/bin/
            golangci-lint run -E gofmt -E unconvert -E misspell -E whitespace -E golint --exclude-use-default=false
      - run: gotestsum
